name: Deploy lambda[Staging]
on:
  push

jobs:

  test-build:
    runs-on: ubuntu-latest
    name: Test Lambda function
    steps:
      - name: Check build status
        run: |
          echo "hello"
    
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: true 
  
      - name: Echo changed files
        run: echo ${{ steps.get_changed.outputs.changed }}