name: Deploy lambda[Staging]
on:
  push

jobs:

  test-build:
    runs-on: ubuntu-latest
    name: Test Lambda function
    steps:
      # - name: Check build status
      #   run: |
      #     echo "hello"
    
      # - uses: Stockopedia/action-get-changed-files@v1
      #   id: get_changed
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     ignore: "**/.github/)"
      #     foldersOnly: true 
      #     format: json
      
      # - name: Echo changed files
      #   run: echo ${{ steps.get_changed.outputs.changed }}
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"
      
      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}