name: 'Deploy'

on:
  push:
    branches:
      - path-ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check which services were modified
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            changed:
              - 'lambda_functions/function1/**'
              - 'lambda_functions/function2/**'
      
      - name: Deploy changed services
        if: ${{ steps.filter.outputs.changed == 'true' }}
        run: |
          echo "All changes:"
          for i in ${{ steps.filter.outputs.changed_files }}; do echo $i ; done