name: CI

on:
  push:
    paths:
      - 'lambda_functions/function1/**'
      - 'lambda_functions/function2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the path of the changed files
      - name: Get changed files
        run: echo "Changed files: ${{ steps.files.outputs.files }}"
        id: files
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      # Add more steps for your CI process here
